spring:
  application:
    name: DrunkHouse

  #데이터베이스 설정
  datasource:
    url: jdbc:mysql://drunkhouse.ctga0qwk0fu1.ap-northeast-2.rds.amazonaws.com:3306/drunkhouse
    username: admin
    password: Op95126522*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

#s3
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2UC3C7EED3L3ZOMW
      secret-key: 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
    stack:
      auto: false
    s3:
      bucket: itbank-pethub-s3

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace




